### ISSUE TITLE
Create controller

### ISSUE THREAD

**Issue by WoongGun** [ltamm/ConveyorBelt#3]
fps controller can be put in I think

**Comment by WoongGun** [comment]
only view movements by mouse, no body control (i.e. remove wasd)

**Comment by ltamm** [comment]
I think the camera position might need adjustment for a good first-person perspective. I wasn't sure of the best location for the camera.

**Comment by WoongGun** [comment]
playerController branch has a fps controller with 0 move and 0 jump that can look around with mouselook
